DROP SCHEMA IF EXISTS `jdbc-application`;
CREATE SCHEMA `jdbc-application`;
USE `jdbc-application`;
CREATE TABLE CUSTOMER (
	ID int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME varchar(255),
    LAST_NAME varchar(255)
);
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Robin', 'Barker');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Tanner', 'Russell');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Kris', 'Gill');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Skye', 'Hayes');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Drew', 'Mayer');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Vic', 'Blanchard');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Aubrey', 'Mccall');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rudy', 'Cook');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Aaren', 'Gibson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rene', 'Scott');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Jordan', 'Evans');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Alex', 'Price');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Elliot', 'Harmon');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rudy', 'Buckley');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rene', 'Burnett');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Harper', 'Ruiz');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Fran', 'Sandoval');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Brynn', 'Fletcher');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Angel', 'Mitchell');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Carmen', 'Wilson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Aubrey', 'Wilkinson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Chris', 'Kaur');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rory', 'Stone');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Gail', 'Jenkins');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Aiden', 'Davidson');
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME) VALUES ('Rory', 'Wyatt');
SELECT * FROM CUSTOMER;